spring:
  datasource:
    url: jdbc:mysql://133.186.211.156:3306/final_exam9
    username: final_exam9
    password: NxXXOnaM7@uxOJw9
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 10
      max-total: 10

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---

spring:
  config:
    activate:
      on-profile: dev

date:
  format: yyyy-MM-dd

---

spring:
  config:
    activate:
      on-profile: real

date:
  format: yyyy-MM-dd hh:mi:ss

