spring:
  datasource:
    url: jdbc:mysql://133.186.211.156:3306/final_exam9
    username: final_exam9
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 10
      max-total: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        